name: Keep Render Backend Awake

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping Render API
        run: |
          curl -s --max-time 10 https://love-calculator-api.onrender.com || echo "Ping failed"
